import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://127.0.0.1:4173/about', { waitUntil: 'load', timeout: 30000 });
await p.waitForTimeout(2500);
const t = await p.evaluate(() => document.body.innerText);
console.log('Shop by Specialty removed:', !/Shop by Specialty|WHAT WE STOCK/i.test(t));
console.log('headings:', (t.match(/\n[A-Z][A-Z&' ]{6,}\n/g)||[]).map(s=>s.trim()).filter(s=>!s.includes('MAMTA')&&!s.includes('SINGH')).join(' / '));
console.log('stats intact:', /Dentzoo in Numbers/.test(t), '| pageerrors:', errs.length);
await b.close();
